###
# Add one customer
POST http://localhost:8080/api/v1/customer
Content-Type: application/json

{"id" :  "200", "firstName" :  "Yang", "lastName" : "W", "email" :  "wy@xyz.com"}

###
# List all customers
GET http://localhost:8080/api/v1/customer
Accept: application/json

###
# Get one customer
GET http://localhost:8080/api/v1/customer/200

###
# Add one customer

###
# List all orders
GET http://localhost:8080/api/v1/order
Accept: application/json

###
GET http://localhost:8080/hello
